### ISSUE TITLE
Cannot set properties of undefined (setting 'binaryType') 

### ISSUE THREAD

**Issue by jensenhertz** [synonymdev/dht-universal#7]
I'm having trouble getting this to work on a browser. When I try to create DHT, it seems that DHT class is not getting `opts.socket` leading to the error below. Any ideas what's the problem?

Code:
```typescript
import { DHT } from 'dht-universal'
const dht = new DHT({ relay: 'ws://127.0.0.1:50000/' })
const swarm = new Hyperswarm({ dht })
```

Error:
```
Uncaught TypeError: Cannot set properties of undefined (setting 'binaryType')
    at new Stream (ws.jss:9:1)
    at new DHT (relay.jss:12:1)
```

**Comment by Nuhvi** [comment]
Can you try 

```js
const dht = await DHT.create({
  relays: ['wss://dht-relay.example.com/'],
  ...opts,
});
```

And can I see the code for the relay setup?

**Comment by jensenhertz** [comment]
Thanks for super fast reply, that solved the problem, thank you!

The relay setup is just copypasta from your example and it's working beautifully. Thanks for making this library happen!
